### ISSUE TITLE
Can you share the actual source code?

### ISSUE THREAD

**Issue by vfbsilva** [Alpkant/Offline-Signature-Verification-on-Real-World-Documents#1]
I've read the paper and im super interested but the source would be a major asset is it  available?

**Comment by Alpkant** [comment]
Thank you for your interest. I shared the dataset and model files which are the essentials for the paper. Unfortunately, training code and pretrained models are not available. It's a huge drawback but It is not possible to publish the source. However, using the details from the paper you can train the model yourself.
